### ISSUE TITLE
Add test automation

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/php-api-client#10]
In order to check for correctness of the library the tests should be executed whenever a new release of AzuraCast is available (can we do this with some kind of trigger?).

- Add TravisCi setup
- Start AzuraCast stack on Travis
- Run tests on that stack

**Comment by BusterNeece** [comment]
@Vaalyn The Travis CI has been updated to spin up its own dedicated AzuraCast instance, preload it with the necessary data and configuration (and a testing API key), then test against _that_ installation, ensuring there is no dependency with third-party installs during the CI/build process.
