### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by olliedean** [AzuraCast/php-api-client#11]
When trying to run "composer require 'azuracast/php-api-client:*'" I get this error:
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for azuracast/php-api-client * -> satisfiable by azuracast/php-api-client[dev-master].
    - Removal request for azuracast/php-api-client == 9999999-dev

Installation failed, reverting ./composer.json to its original content.

**Comment by olliedean** [comment]
I fixed this issue, now I am getting:
[11-Jul-2019 20:30:59 UTC] PHP Fatal error:  Uncaught AzuraCast\Api\Exception\ClientRequestException: Call to "nowplaying" returned non-successful response with code 404 and body: 


<!DOCTYPE html>
<html>
    <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta http-equiv="Cache-control" content="no-cache">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 Not Found</title>
    <style type="text/css">
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            line-height: 1.428571429;
            background-color: #ffffff;
            color: #2F3230;
            padding: 0;
            margin: 0;
        }
        section, footer {
            display: block;
            padding: 0;
            margin: 0;
        }
        .container {
            margin-left: auto;
            margin-right: auto;
            padding: 0 10px;
         in /home/itspower/vendor/azuracast/php-api-client/src/AbstractClient.php on line 62

**Comment by Vaalyn** [comment]
Hey, would you mind showing me how you initialize the Client?

**Comment by oussamatn** [comment]
Hello, I'm facing the same problem. I cant install the package locally via composer.
I got :
```
[InvalidArgumentException]                                                   
  Could not find package azuracast/php-api-client at any version for your min  
  imum-stability (stable). Check the package spelling or your minimum-stabili  
  ty 
```

**Comment by Vaalyn** [comment]
We don't have a release published yet so you'll need to use `composer require azuracast/php-api-client:dev-master`

**Comment by olliedean** [comment]
> Hey, would you mind showing me how you initialize the Client?

```
include('../../vendor/autoload.php');

$api = \AzuraCast\Api\Client::create(
	'radio.itspower.net',
	'*********************'
);

$nowPlaying = $api->nowPlaying();

echo $nowPlaying->getCurrentSong()->getSong()->getTitle();

```
the ***************** is just my API key value. I'm not sure what I'm doing wrong

**Comment by Vaalyn** [comment]
Seems okay to me.

We had some updates in the last days. Have you tried updating to the newest commit version?
If you are already on the newest version could you try adding `https://` before the host? Maybe the redirect from http to https is not working correctly.

This call will fail too:

```
echo $nowPlaying->getCurrentSong()->getSong()->getTitle();
```

The `nowPlaying()` method returns an array with the data from all stations.
If you only need the current song from a single station you should use:

```
$api->station(1)->nowPlaying();
```

**Comment by olliedean** [comment]
Followed what you said, updated from 85d999c to 6e6144b, put https:// infront of the host, and changed the method, and now i'm getting this:
[19-Jul-2019 09:28:35 UTC] PHP Notice:  Undefined index: path in /home/itspower/vendor/azuracast/php-api-client/src/Dto/MountDto.php on line 186
[19-Jul-2019 09:28:35 UTC] PHP Recoverable fatal error:  Object of class AzuraCast\Api\Dto\NowPlayingDto could not be converted to string in /home/itspower/public_html/*********/playground.php on line 10

**Comment by Vaalyn** [comment]
This warning should be fixed now.
```
[19-Jul-2019 09:28:35 UTC] PHP Notice: Undefined index: path in /home/itspower/vendor/azuracast/php-api-client/src/Dto/MountDto.php on line 186
```

This is most likely in an error in your code. Make sure that you use echo only on something like a string and not an object. 
```
[19-Jul-2019 09:28:35 UTC] PHP Recoverable fatal error: Object of class AzuraCast\Api\Dto\NowPlayingDto could not be converted to string in /home/itspower/public_html/*********/playground.php on line 10
```

**Comment by olliedean** [comment]
Works now! Thanks :)
