### ISSUE TITLE
Undefined index on station()->listeners()

### ISSUE THREAD

**Issue by HuckinB** [AzuraCast/php-api-client#23]
Bug: 
Upon trying to return the Listeners of a station, there is an undefined index 'lat' within the LocationDto at 
['src\Dto\LocationDto.php' line 247'](https://github.com/AzuraCast/php-api-client/blob/d51808f2e6794e1ae80b55ab353c67f153bd05da/src/Dto/LocationDto.php#L247)

I believe this to be a simple bug where properties have been changed within updates.

Steps to reproduce:

`dd(Client()->station(1)->listeners());`

Regards,

@HuckinB | @KylePython

**Comment by HuckinB** [comment]
@SlvrEagle23 - Are you able to attend this issue at some point when you get some free time please.

**Comment by Vaalyn** [comment]
Fixed by https://github.com/AzuraCast/php-api-client/commit/ea1f472ea80e2529c39610f7bcc893e829759368 and available by updating to [2.0.2](https://github.com/AzuraCast/php-api-client/releases/tag/2.0.2)

**Comment by HuckinB** [comment]
Thankyou ❤️
