### ISSUE TITLE
Use without Composer

### ISSUE THREAD

**Issue by AndyRixon** [AzuraCast/php-api-client#34]
Not really an issue or a bug.

I was wondering if there was a way to be able to use this without the need for composer? I ask as I would love to make this work as a WHMCS module.

Many Thanks
Andy

**Comment by BusterNeece** [comment]
We have no plans to distribute this in a way that wouldn't use Composer, though you absolutely could just use Composer to load the dependencies and then dump the vendor directory in with the other files.

**Comment by AndyRixon** [comment]
I've managed to create a simple whmcs server provisioning module for AzuraCast... by simple I mean it is bare minimum but it does work and I will continue to work on it and add more and more features.

[You can view the module here](https://git.tidynode.co.uk/AndyRixon/azuracast-whmcs-module)
